### ISSUE TITLE
Suggestion: Create a repo to maintain e2e test scenarios, how to setup environment 

### ISSUE THREAD

**Issue by cmoulliard** [redhat-buildpacks/builders-spike#2]
## Suggestion

I would like to propose to create a github repo under this organization to allow to:

- Maintain e2e test cases able to validate our buildpacks running with tekton, shipwright, ...
- Test our runtimes + buildpacks according to samples (= representative of the build supported)
- How to setup an environment to play with "buildpacks" on ocp, k8s (simple build-pod, ...)
- How to use pack with new Lifecycle releases
- ...
WDYT ? @lance @quintesse @sbose78 @zroubalik

**Comment by lance** [comment]
That sounds great to me @cmoulliard - go for it!

**Comment by sbose78** [comment]
Sounds great!

**Comment by cmoulliard** [comment]
Ok. I will setup such a new git repo then and move what I developed there

**Comment by cmoulliard** [comment]
Repo created: https://github.com/redhat-buildpacks/testing @lance @sbose78
